#!/usr/bin/env python
"""
Converts chat_session.jsonl into chat_session.md — a human-readable
markdown file suitable for viewing on GitHub.

Usage: python format_session.py [input.jsonl] [output.md]
Defaults: chat_session.jsonl -> chat_session.md (in current directory)

Stdlib only — no external dependencies.
"""
import json
import sys
import os


def format_tool_use(tool):
    name = tool.get('name', 'unknown')
    inp = tool.get('input', {})
    if name == 'Bash':
        cmd = inp.get('command', '')
        return f"**`$ {cmd}`**"
    elif name in ('Read', 'Glob', 'Grep'):
        return f"**{name}**: `{inp.get('file_path', inp.get('pattern', inp.get('path', '')))}`"
    elif name in ('Edit', 'Write'):
        return f"**{name}**: `{inp.get('file_path', '')}`"
    else:
        # Truncate large inputs
        s = json.dumps(inp, indent=2)
        if len(s) > 500:
            s = s[:500] + '\n...(truncated)'
        return f"**{name}**:\n```json\n{s}\n```"


def format_content_block(block):
    btype = block.get('type', '')
    if btype == 'text':
        return block.get('text', '')
    elif btype == 'tool_use':
        return format_tool_use(block)
    elif btype == 'tool_result':
        content = block.get('content', '')
        if isinstance(content, list):
            parts = []
            for c in content:
                if isinstance(c, dict) and c.get('type') == 'text':
                    parts.append(c.get('text', ''))
            content = '\n'.join(parts)
        if isinstance(content, str) and len(content) > 1000:
            content = content[:1000] + '\n...(truncated)'
        return f"```\n{content}\n```" if content else ''
    return ''


def convert(input_path, output_path):
    entries = []
    with open(input_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                continue

    lines = ['# Claude Agent Session Log\n']

    for entry in entries:
        etype = entry.get('type', '')

        if etype == 'user':
            msg = entry.get('message', {})
            content = msg.get('content', '')
            if isinstance(content, str):
                lines.append(f'## User\n\n{content}\n')
            elif isinstance(content, list):
                parts = [format_content_block(b) for b in content]
                lines.append(f'## User\n\n' + '\n\n'.join(p for p in parts if p) + '\n')

        elif etype == 'assistant':
            msg = entry.get('message', {})
            content = msg.get('content', [])
            if isinstance(content, str):
                lines.append(f'## Assistant\n\n{content}\n')
            elif isinstance(content, list):
                parts = []
                for block in content:
                    formatted = format_content_block(block)
                    if formatted:
                        parts.append(formatted)
                if parts:
                    lines.append('## Assistant\n\n' + '\n\n'.join(parts) + '\n')

        elif etype == 'result':
            # Tool results
            result = entry.get('result', entry.get('content', ''))
            if isinstance(result, str) and result.strip():
                if len(result) > 2000:
                    result = result[:2000] + '\n...(truncated)'
                lines.append(f'### Tool Output\n\n```\n{result}\n```\n')

    lines.append('\n---\n*Generated by choline format_session.py*\n')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))


if __name__ == '__main__':
    inp = sys.argv[1] if len(sys.argv) > 1 else 'chat_session.jsonl'
    out = sys.argv[2] if len(sys.argv) > 2 else 'chat_session.md'
    if os.path.exists(inp):
        convert(inp, out)
    else:
        print(f"No file found: {inp}")
